### ISSUE TITLE
Teclado abre ao retornar para o aplicativo

### ISSUE THREAD

**Issue by edulima01** [dtidigitalcrafters/gestao-competencias#23]
Ao ir para um outro aplicativo, e voltar pra ele, o teclado abre e fica aberto, mesmo não tendo nenhum campo.

**Comment by vitorricoy** [comment]
Corrigido temporariamente, através de chamadas à interface com o SO, no pull request #30 . Esse bug está ocorrendo devido a um comportamento inesperado da framework.
