### ISSUE TITLE
Não é possível desmarcar o nível de uma skill após selecionar a mesma.

### ISSUE THREAD

**Issue by vinicius-queiroz93** [dtidigitalcrafters/gestao-competencias#26]
Na tela onde selecionamos o nível de habilidade de um tópico através do sistema de estrelas, após marcar alguma quantidade arbitrária de estrelas em qualquer tópico, é impossível voltar para 0 estrelas naquele tópico.

**Comment by vitorricoy** [comment]
Corrigido no pull request #29
